# Default values for dieroll.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

metadata:
  namespace: dieroll
  appVersion: "1.0"

replicas:
  replicaCount: 1

image:
  repository: nexus-repo.localhost/dieroll
  tag: "latest"
  pullPolicy: Always

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000
  internalport: 3000
  externalport: 80

ingress:
  enabled: true
  path: /*
  hosts:
    - localhost
  tls: []
